"""Add Schedule and Announcement tables

Revision ID: d515aa395d7c
Revises: 6ed66f8397e3
Create Date: 2025-10-07 10:21:09.346391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd515aa395d7c'
down_revision: Union[str, Sequence[str], None] = '6ed66f8397e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
